/* Generated by the Nim Compiler v2.2.4 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI570425949 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI570425666 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554445 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI570425374 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217742 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI570425385 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI570425373 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI570426216 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI570425372 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null},
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null},
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null},
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null},
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;
var NNI570425372 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "label", len: 0, typ: NTI33554449, name: "label", sons: null},
{kind: 1, offset: "active", len: 0, typ: NTI33554466, name: "active", sons: null}]};
NTI570425372.node = NNI570425372;
NTI570425385.base = NTI33554435;
var NNI570425373 = {kind: 1, offset: "seats", len: 0, typ: NTI570425385, name: "seats", sons: null};
NTI570425373.node = NNI570425373;
NTI570426216.base = NTI570425373;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555172;
var NNI134217742 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217742.node = NNI134217742;
NTI134217742.base = NTI134217741;
var NNI570425374 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "index", len: 0, typ: NTI33554435, name: "index", sons: null},
{kind: 1, offset: "games", len: 0, typ: NTI33554435, name: "games", sons: null},
{kind: 1, offset: "tie", len: 0, typ: NTI33554445, name: "tie", sons: null}]};
NTI570425374.node = NNI570425374;
NTI570425666.base = NTI33554435;
NTI570425949.base = NTI33554435;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;



}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557330 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2878(ti_p2))) {
      result_33557330 = src_p1;
      }
      else {
        result_33557330 = [src_p1[0], src_p1[1]];
      }

      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557330 = dest_p0;

      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557330 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557330 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557330, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) {
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557330 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557330 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557330 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
          }
        }
      }

      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557330 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557330 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557330[i] = nimCopy(result_33557330[i], src_p1[i], ti_p2.base);
        }
      }

      break;
    case 28:
            if (src_p1 !== null) {
        result_33557330 = src_p1.slice(0);
      }

      break;
    default:
      result_33557330 = src_p1;
      break;
    }

  return result_33557330;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;



}

function isObj(obj_p0, subclass_p1) {
  var result_33557443 = false;

  BeforeRet: {
    var x_33557444 = obj_p0;
    if ((x_33557444 == subclass_p1)) {
    result_33557443 = true;
    break BeforeRet;
    }

    Label1: {
        Label2: while (true) {
        if (!!((x_33557444 == subclass_p1))) break Label2;
          if ((x_33557444 == null)) {
          result_33557443 = false;
          break BeforeRet;
          }

          x_33557444 = x_33557444.base;
        }
    };
    result_33557443 = true;
    break BeforeRet;
  };

  return result_33557443;

}

function toJSStr(s_p0) {
  var result_33556919 = null;

    var res_33556973 = newSeq__system_u2516((s_p0).length);
    var i_33556974 = 0;
    var j_33556975 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556974 < (s_p0).length)) break Label2;
          var c_33556976 = s_p0[i_33556974];
          if ((c_33556976 < 128)) {
          res_33556973[j_33556975] = String.fromCharCode(c_33556976);
          i_33556974 += 1;
          }
          else {
            var helper_33557002 = newSeq__system_u2516(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557003 = c_33556976.toString(16);
                  if ((((code_33557003) == null ? 0 : (code_33557003).length) == 1)) {
                  helper_33557002.push("%0");;
                  }
                  else {
                  helper_33557002.push("%");;
                  }

                  helper_33557002.push(code_33557003);;
                  i_33556974 += 1;
                  if ((((s_p0).length <= i_33556974) || (s_p0[i_33556974] < 128))) {
                  break Label3;
                  }

                  c_33556976 = s_p0[i_33556974];
                }
            };
++excHandler;
            try {
            res_33556973[j_33556975] = decodeURIComponent(helper_33557002.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556973[j_33556975] = helper_33557002.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }

          j_33556975 += 1;
        }
    };
    if (res_33556973.length < j_33556975) { for (var i = res_33556973.length ; i < j_33556975 ; ++i) res_33556973.push(null); }
               else { res_33556973.length = j_33556975; };
    result_33556919 = res_33556973.join("");

  return result_33556919;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }

    throw e_p0;


}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;



}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557370 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557370 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }

  };

  return result_33557370;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557365 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557365 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }

  };

  return result_33557365;

}
    var PolicyLetters_570425366 = [[65], [66], [67], [68], [69], [70], [71], [72], [73], [74], [75], [76], [77], [78], [79]];

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;



}

function addChar(x_p0, c_p1) {
    x_p0.push(c_p1);


}

function divInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 / b_p1);



}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;



}
var ConstSet2 = setConstr(46, 44);

function nimMax(a_p0, b_p1) {
    var Temporary1;

  var result_33557157 = 0;

  BeforeRet: {
    if ((b_p1 <= a_p0)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }

    result_33557157 = Temporary1;
    break BeforeRet;
  };

  return result_33557157;

}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;



}
            var HeatLowColor_570425364 = new Int32Array([255, 255, 248]);

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;



}
            var HeatHighColor_570425365 = new Int32Array([17, 17, 17]);

function modInt(a_p0, b_p1) {
        if (b_p1 == 0) raiseDivByZero();
    if (b_p1 == -1 && a_p0 == 2147483647) raiseOverflow();
    return Math.trunc(a_p0 % b_p1);



}

function nimMin(a_p0, b_p1) {
    var Temporary1;

  var result_33557153 = 0;

  BeforeRet: {
    if ((a_p0 <= b_p1)) {
    Temporary1 = a_p0;
    }
    else {
    Temporary1 = b_p1;
    }

    result_33557153 = Temporary1;
    break BeforeRet;
  };

  return result_33557153;

}

function isFatPointer__system_u2878(ti_p0) {
  var result_33557312 = false;

  BeforeRet: {
    result_33557312 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557312;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);

      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }

      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }

      break;
    }


}

function add__system_u1942(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }



}

function newSeq__system_u2516(len_p0) {
  var result_33556952 = [];

    result_33556952 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556952[i] = null; }
  return result_33556952;

}

function isNimException__system_u2017() {
    return lastJSError && lastJSError.m_type;


}

function getCurrentException() {
  var result_33556452 = null;

    if (isNimException__system_u2017()) {
    result_33556452 = lastJSError;
    }


  return result_33556452;

}

function raiseDefect() {
    if (isNimException__system_u2017()) {
    var e_33556664 = getCurrentException();
    if (isObj(e_33556664.m_type, NTI33555172)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556664);
    }

    throw e_33556664;
    }

    }



}

function unhandledException(e_p0) {
    var buf_33556658 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556658[0].push.apply(buf_33556658[0], e_p0.message);;
    }
    else {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }

    buf_33556658[0].push.apply(buf_33556658[0], [32,91]);;
    add__system_u1942(buf_33556658, 0, e_p0.name);
    buf_33556658[0].push.apply(buf_33556658[0], [93,10]);;
    var cbuf_33556659 = toJSStr(buf_33556658[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556659);
  }
  else {
    throw cbuf_33556659;
  }



}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");


}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();



}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");


}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_301990096 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_570426948 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_570426948 < n_p3)) break Label4;
            iHEX60gensym4_301990110 = i_570426948;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            i_570426948 = addInt(i_570426948, 1);
          }
      };
    };


}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));


}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));


}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));


}

function HEX24__systemZdollars_u14(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

    result_385875984[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_385875984, 0, xHEX60gensym0_p0);

  return result_385875984[0];

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u14(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u14(a_p1),[32,46,46,32],HEX24__systemZdollars_u14(b_p2));
    }

    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");


}

function policyLabel__main_u111(index_p0) {
  var result_570425457 = [];

    result_570425457 = nimCopy(null, ([80,111,108,105,99,121,32]).concat(PolicyLetters_570425366[chckIndx(index_p0, 0, (PolicyLetters_570425366).length - 1)]), NTI33554449);

  return result_570425457;

}

function initState__main_u1488() {
    Label1: {
      var i_570426837 = 0;
      var i_570426942 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426942 < 15)) break Label3;
            i_570426837 = i_570426942;
            state_570425401[0].policies[chckIndx(i_570426837, 0, (state_570425401[0].policies).length - 1)] = nimCopy(state_570425401[0].policies[chckIndx(i_570426837, 0, (state_570425401[0].policies).length - 1)], {label: policyLabel__main_u111(i_570426837), active: (i_570426837 < 8)}, NTI570425372);
            i_570426942 = addInt(i_570426942, 1);
          }
      };
    };
    state_570425401[0].games = nimCopy(null, [], NTI570426216);
    state_570425401[0].sliderGames = 1;
    state_570425401[0].targetPairGames = 10;
    state_570425401[0].allocationType = 0;
    state_570425401[0].autoRunning = false;
    state_570425401[0].autoTimerId = 0;
    state_570425401[0].autoSteps = 0;
    state_570425401[0].message = nimCopy(null, [], NTI33554449);


}

function clampInt__main_u98(value_p0, low_p1, high_p2) {
    var Temporary1;

  var result_570425446 = 0;

    if ((value_p0 < low_p1)) {
    Temporary1 = low_p1;
    }
    else {
    if ((high_p2 < value_p0)) {
    Temporary1 = high_p2;
    }
    else {
    Temporary1 = value_p0;
    }
    }
    result_570425446 = Temporary1;

  return result_570425446;

}

function gameIncluded__main_u253(game_p0) {
  var result_570425599 = false;

  BeforeRet: {
    Label1: {
      var index_570425642 = 0;
      var i_570426968 = 0;
      Label2: {
          Label3: while (true) {
          if (!true) break Label3;
            index_570425642 = game_p0.seats[chckIndx(i_570426968, 0, (game_p0.seats).length - 1)];
            if (!(state_570425401[0].policies[chckIndx(index_570425642, 0, (state_570425401[0].policies).length - 1)].active)) {
            result_570425599 = false;
            break BeforeRet;
            }

            if ((7 <= i_570426968)) {
            break Label2;
            }

            i_570426968 += 1;
          }
      };
    };
    result_570425599 = true;
  };

  return result_570425599;

}

function sysFatal__stdZassertions_u44(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");


}

function raiseAssert__stdZassertions_u42(msg_p0) {
    sysFatal__stdZassertions_u44(msg_p0);


}

function failedAssertImpl__stdZassertions_u84(msg_p0) {
    raiseAssert__stdZassertions_u42(msg_p0);


}

function computeCounts__main_u377() {
  var result_570425722 = [new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15), new Int32Array(15)];

    Label1: {
      var game_570425726 = ({seats: new Int32Array(8)});
      var i_570426963 = 0;
      var L_570426964 = (state_570425401[0].games).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426963 < L_570426964)) break Label3;
            game_570425726 = state_570425401[0].games[chckIndx(i_570426963, 0, (state_570425401[0].games).length - 1)];
            Label4: {
              if (!(gameIncluded__main_u253(game_570425726))) {
              break Label4;
              }

              Label5: {
                var i_570425731 = 0;
                var i_570426960 = 0;
                Label6: {
                    Label7: while (true) {
                    if (!(i_570426960 < 8)) break Label7;
                      i_570425731 = i_570426960;
                      Label8: {
                        var j_570425736 = 0;
                        var colontmp__570426957 = 0;
                        colontmp__570426957 = addInt(i_570425731, 1);
                        var i_570426958 = colontmp__570426957;
                        Label9: {
                            Label10: while (true) {
                            if (!(i_570426958 < 8)) break Label10;
                              j_570425736 = i_570426958;
                              var a_570425737 = game_570425726.seats[chckIndx(i_570425731, 0, (game_570425726.seats).length - 1)];
                              var b_570425738 = game_570425726.seats[chckIndx(j_570425736, 0, (game_570425726.seats).length - 1)];
                              result_570425722[chckIndx(a_570425737, 0, (result_570425722).length - 1)][chckIndx(b_570425738, 0, (result_570425722[chckIndx(a_570425737, 0, (result_570425722).length - 1)]).length - 1)] = addInt(result_570425722[chckIndx(a_570425737, 0, (result_570425722).length - 1)][chckIndx(b_570425738, 0, (result_570425722[chckIndx(a_570425737, 0, (result_570425722).length - 1)]).length - 1)], 1);
                              result_570425722[chckIndx(b_570425738, 0, (result_570425722).length - 1)][chckIndx(a_570425737, 0, (result_570425722[chckIndx(b_570425738, 0, (result_570425722).length - 1)]).length - 1)] = addInt(result_570425722[chckIndx(b_570425738, 0, (result_570425722).length - 1)][chckIndx(a_570425737, 0, (result_570425722[chckIndx(b_570425738, 0, (result_570425722).length - 1)]).length - 1)], 1);
                              i_570426958 = addInt(i_570426958, 1);
                            }
                        };
                      };
                      i_570426960 = addInt(i_570426960, 1);
                    }
                };
              };
            };
            i_570426963 += 1;
            if (!(((state_570425401[0].games).length == L_570426964))) {
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }

          }
      };
    };

  return result_570425722;

}

function activeGameCount__main_u315() {
  var result_570425660 = 0;

    Label1: {
      var game_570425683 = ({seats: new Int32Array(8)});
      var i_570426971 = 0;
      var L_570426972 = (state_570425401[0].games).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426971 < L_570426972)) break Label3;
            game_570425683 = state_570425401[0].games[chckIndx(i_570426971, 0, (state_570425401[0].games).length - 1)];
            if (gameIncluded__main_u253(game_570425683)) {
            result_570425660 = addInt(result_570425660, 1);
            }

            i_570426971 += 1;
            if (!(((state_570425401[0].games).length == L_570426972))) {
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }

          }
      };
    };

  return result_570425660;

}

function activeCount__main_u130() {
  var result_570425475 = 0;

    Label1: {
      var policy_570425502 = ({label: [], active: false});
      var i_570426976 = 0;
      Label2: {
          Label3: while (true) {
          if (!true) break Label3;
            policy_570425502 = nimCopy(policy_570425502, state_570425401[0].policies[chckIndx(i_570426976, 0, (state_570425401[0].policies).length - 1)], NTI570425372);
            if (policy_570425502.active) {
            result_570425475 = addInt(result_570425475, 1);
            }

            if ((14 <= i_570426976)) {
            break Label2;
            }

            i_570426976 += 1;
          }
      };
    };

  return result_570425475;

}

function canPlay__main_u1169() {
  var result_570426514 = false;

    result_570426514 = ((0 < state_570425401[0].sliderGames) && (8 <= activeCount__main_u130()));

  return result_570426514;

}

function canRemove__main_u1171(includedGames_p0) {
  var result_570426517 = false;

    result_570426517 = ((0 < state_570425401[0].sliderGames) && (0 < includedGames_p0));

  return result_570426517;

}

function canAutoEqualize__main_u1395() {
  var result_570426740 = false;

    result_570426740 = (state_570425401[0].autoRunning || (8 <= activeCount__main_u130()));

  return result_570426740;

}

function policyInputId__main_u108(index_p0) {
  var result_570425454 = [];

    result_570425454 = nimCopy(null, ([112,111,108,105,99,121,45,99,104,101,99,107,45]).concat(HEX24__systemZdollars_u14(index_p0)), NTI33554449);

  return result_570425454;

}

function escapeHtml__main_u94(text_p0) {
  var result_570425440 = [];

    Label1: {
      var ch_570425441 = 0;
      var i_570426984 = 0;
      var L_570426985 = (text_p0).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426984 < L_570426985)) break Label3;
            ch_570425441 = text_p0[chckIndx(i_570426984, 0, (text_p0).length - 1)];
            switch (ch_570425441) {
            case 38:
              result_570425440.push.apply(result_570425440, [38,97,109,112,59]);;
              break;
            case 60:
              result_570425440.push.apply(result_570425440, [38,108,116,59]);;
              break;
            case 62:
              result_570425440.push.apply(result_570425440, [38,103,116,59]);;
              break;
            case 34:
              result_570425440.push.apply(result_570425440, [38,113,117,111,116,59]);;
              break;
            case 39:
              result_570425440.push.apply(result_570425440, [38,35,51,57,59]);;
              break;
            default:
              addChar(result_570425440, ch_570425441);;
              break;
            }
            i_570426984 += 1;
            if (!(((text_p0).length == L_570426985))) {
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(272, 11) `len(a) == L` the length of the string changed while iterating over it"));
            }

          }
      };
    };

  return result_570425440;

}

function raiseDivByZero() {
    raiseException({message: [100,105,118,105,115,105,111,110,32,98,121,32,122,101,114,111], parent: null, m_type: NTI134217742, name: null, trace: [], up: null}, "DivByZeroDefect");


}

function policyGameCount__main_u418(counts_p0, index_p1) {
  var result_570425765 = 0;

  BeforeRet: {
    if (!(state_570425401[0].policies[chckIndx(index_p1, 0, (state_570425401[0].policies).length - 1)].active)) {
    result_570425765 = 0;
    break BeforeRet;
    }

    var pairs_570425766 = 0;
    Label1: {
      var j_570425771 = 0;
      var i_570426988 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426988 < 15)) break Label3;
            j_570425771 = i_570426988;
            if (!((index_p1 == j_570425771))) {
            pairs_570425766 = addInt(pairs_570425766, counts_p0[chckIndx(index_p1, 0, (counts_p0).length - 1)][chckIndx(j_570425771, 0, (counts_p0[chckIndx(index_p1, 0, (counts_p0).length - 1)]).length - 1)]);
            }

            i_570426988 = addInt(i_570426988, 1);
          }
      };
    };
    result_570425765 = divInt(pairs_570425766, 7);
  };

  return result_570425765;

}

function renderPolicyTable__main_u1085(counts_p0) {
            var Temporary4;
            var Temporary5;

  var result_570426431 = [];

    result_570426431.push.apply(result_570426431, [60,116,97,98,108,101,32,99,108,97,115,115,61,34,114,101,112,111,114,116,45,116,97,98,108,101,32,119,105,100,101,32,112,111,108,105,99,121,45,115,117,109,109,97,114,121,32,110,111,45,115,111,114,116,34,62,10]);;
    result_570426431.push.apply(result_570426431, [60,99,111,108,103,114,111,117,112,62]);;
    result_570426431.push.apply(result_570426431, [60,99,111,108,32,99,108,97,115,115,61,34,112,111,108,105,99,121,45,115,101,108,101,99,116,45,99,111,108,34,62]);;
    result_570426431.push.apply(result_570426431, [60,99,111,108,32,99,108,97,115,115,61,34,112,111,108,105,99,121,45,110,97,109,101,45,99,111,108,34,62]);;
    result_570426431.push.apply(result_570426431, [60,99,111,108,32,99,108,97,115,115,61,34,112,111,108,105,99,121,45,103,97,109,101,115,45,99,111,108,34,62]);;
    result_570426431.push.apply(result_570426431, [60,47,99,111,108,103,114,111,117,112,62,10]);;
    result_570426431.push.apply(result_570426431, [60,116,104,101,97,100,62,60,116,114,62]);;
    result_570426431.push.apply(result_570426431, [60,116,104,62,83,101,108,101,99,116,101,100,60,47,116,104,62]);;
    result_570426431.push.apply(result_570426431, [60,116,104,62,80,111,108,105,99,121,60,47,116,104,62]);;
    result_570426431.push.apply(result_570426431, [60,116,104,62,71,97,109,101,115,60,47,116,104,62]);;
    result_570426431.push.apply(result_570426431, [60,47,116,114,62,60,47,116,104,101,97,100,62,10]);;
    result_570426431.push.apply(result_570426431, [60,116,98,111,100,121,62,10]);;
    Label1: {
      var i_570426438 = 0;
      var policy_570426439 = ({label: [], active: false});
      var i_570426980 = 0;
      Label2: {
          Label3: while (true) {
          if (!true) break Label3;
            i_570426438 = i_570426980;
            policy_570426439 = nimCopy(policy_570426439, state_570425401[0].policies[chckIndx(i_570426980, 0, (state_570425401[0].policies).length - 1)], NTI570425372);
            if (policy_570426439.active) {
            Temporary4 = [];
            }
            else {
            Temporary4 = [32,99,108,97,115,115,61,34,105,110,97,99,116,105,118,101,45,114,111,119,34];
            }

            var rowClass_570426440 = nimCopy(null, Temporary4, NTI33554449);
            if (policy_570426439.active) {
            Temporary5 = [32,99,104,101,99,107,101,100];
            }
            else {
            Temporary5 = [];
            }

            var checked_570426441 = nimCopy(null, Temporary5, NTI33554449);
            result_570426431.push.apply(result_570426431, ([60,116,114]).concat(rowClass_570426440,[62]));;
            result_570426431.push.apply(result_570426431, [60,116,100,32,99,108,97,115,115,61,34,112,111,108,105,99,121,45,99,104,101,99,107,45,99,101,108,108,34,62]);;
            result_570426431.push.apply(result_570426431, ([60,105,110,112,117,116,32,105,100,61,34]).concat(policyInputId__main_u108(i_570426438)));;
            result_570426431.push.apply(result_570426431, ([34,32,116,121,112,101,61,34,99,104,101,99,107,98,111,120,34,32,100,97,116,97,45,112,111,108,105,99,121,45,105,110,100,101,120,61,34]).concat(HEX24__systemZdollars_u14(i_570426438),[34]));;
            result_570426431.push.apply(result_570426431, ([32,97,114,105,97,45,108,97,98,101,108,61,34,83,101,108,101,99,116,32]).concat(escapeHtml__main_u94(policy_570426439.label),[34]));;
            result_570426431.push.apply(result_570426431, (checked_570426441).concat([62,60,47,116,100,62]));;
            result_570426431.push.apply(result_570426431, ([60,116,100,32,99,108,97,115,115,61,34,98,111,116,45,110,97,109,101,32,110,97,109,101,34,62]).concat(escapeHtml__main_u94(policy_570426439.label)));;
            result_570426431.push.apply(result_570426431, [60,47,116,100,62]);;
            result_570426431.push.apply(result_570426431, ([60,116,100,32,99,108,97,115,115,61,34,110,117,109,34,62]).concat(HEX24__systemZdollars_u14(policyGameCount__main_u418(counts_p0, i_570426438)),[60,47,116,100,62]));;
            result_570426431.push.apply(result_570426431, [60,47,116,114,62,10]);;
            if ((14 <= i_570426980)) {
            break Label2;
            }

            i_570426980 += 1;
          }
      };
    };
    result_570426431.push.apply(result_570426431, [60,47,116,98,111,100,121,62,60,47,116,97,98,108,101,62,10]);;

  return result_570426431;

}

function plural__main_u103(count_p0, one_p1, many_p2) {
    var Temporary1;

  var result_570425451 = [];

    if ((count_p0 == 1)) {
    Temporary1 = one_p1;
    }
    else {
    Temporary1 = many_p2;
    }

    result_570425451 = nimCopy(null, Temporary1, NTI33554449);

  return result_570425451;

}

function playButtonText__main_u1077() {
  var result_570426422 = [];

    var noun_570426423 = plural__main_u103(state_570425401[0].sliderGames, [103,97,109,101], [103,97,109,101,115]);
    result_570426422 = nimCopy(null, ([80,108,97,121,32]).concat(HEX24__systemZdollars_u14(state_570425401[0].sliderGames),[32],noun_570426423), NTI33554449);

  return result_570426422;

}

function removeButtonText__main_u1080() {
  var result_570426425 = [];

    var noun_570426426 = plural__main_u103(state_570425401[0].sliderGames, [103,97,109,101], [103,97,109,101,115]);
    result_570426425 = nimCopy(null, ([82,101,109,111,118,101,32]).concat(HEX24__systemZdollars_u14(state_570425401[0].sliderGames),[32],noun_570426426), NTI33554449);

  return result_570426425;

}

function autoButtonText__main_u1083() {
    var Temporary1;

  var result_570426428 = [];

    if (state_570425401[0].autoRunning) {
    Temporary1 = [83,116,111,112];
    }
    else {
    Temporary1 = [65,117,116,111,45,69,113,117,97,108,105,122,101];
    }

    result_570426428 = nimCopy(null, Temporary1, NTI33554449);

  return result_570426428;

}

function renderStatus__main_u1098(includedGames_p0) {
  var result_570426444 = [];

    var active_570426445 = activeCount__main_u130();
    var activeNoun_570426446 = plural__main_u103(active_570426445, [112,111,108,105,99,121], [112,111,108,105,99,105,101,115]);
    var includedNoun_570426447 = plural__main_u103(includedGames_p0, [103,97,109,101], [103,97,109,101,115]);
    var storedNoun_570426451 = plural__main_u103((state_570425401[0].games).length, [103,97,109,101], [103,97,109,101,115]);
    result_570426444.push.apply(result_570426444, ([60,115,112,97,110,62]).concat(HEX24__systemZdollars_u14(active_570426445),[32,97,99,116,105,118,101,32],activeNoun_570426446,[60,47,115,112,97,110,62]));;
    result_570426444.push.apply(result_570426444, ([60,115,112,97,110,62]).concat(HEX24__systemZdollars_u14(includedGames_p0),[32,105,110,99,108,117,100,101,100,32],includedNoun_570426447));;
    result_570426444.push.apply(result_570426444, [60,47,115,112,97,110,62]);;
    result_570426444.push.apply(result_570426444, ([60,115,112,97,110,62]).concat(HEX24__systemZdollars_u14((state_570425401[0].games).length),[32,115,116,111,114,101,100,32],storedNoun_570426451));;
    result_570426444.push.apply(result_570426444, [60,47,115,112,97,110,62]);;
    if ((0 < (state_570425401[0].message).length)) {
    result_570426444.push.apply(result_570426444, ([60,115,112,97,110,62]).concat(escapeHtml__main_u94(state_570425401[0].message),[60,47,115,112,97,110,62]));;
    }


  return result_570426444;

}

function activeIndices__main_u197() {
  var result_570425542 = [];

    Label1: {
      var i_570425588 = 0;
      var policy_570425589 = ({label: [], active: false});
      var i_570426991 = 0;
      Label2: {
          Label3: while (true) {
          if (!true) break Label3;
            i_570425588 = i_570426991;
            policy_570425589 = nimCopy(policy_570425589, state_570425401[0].policies[chckIndx(i_570426991, 0, (state_570425401[0].policies).length - 1)], NTI570425372);
            if (policy_570425589.active) {
            result_570425542.push(i_570425588);;
            }

            if ((14 <= i_570426991)) {
            break Label2;
            }

            i_570426991 += 1;
          }
      };
    };

  return result_570425542;

}

function autoLowTarget__main_u432() {
  var result_570425777 = 0.0;

    result_570425777 = (state_570425401[0].targetPairGames * 0.9);

  return result_570425777;

}

function autoHighTarget__main_u434() {
  var result_570425779 = 0.0;

    result_570425779 = (state_570425401[0].targetPairGames * 1.1);

  return result_570425779;

}

function computePairStats__main_u436(counts_p0, active_p1) {
  var result_570425783 = ({pairs: 0, total: 0, inside: 0, below: 0, above: 0, average: 0.0});

    var low_570425784 = autoLowTarget__main_u432();
    var high_570425785 = autoHighTarget__main_u434();
    Label1: {
      var i_570425794 = 0;
      var colontmp__570426999 = 0;
      colontmp__570426999 = (active_p1).length;
      var i_570427000 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427000 < colontmp__570426999)) break Label3;
            i_570425794 = i_570427000;
            Label4: {
              var j_570425802 = 0;
              var colontmp__570426995 = 0;
              var colontmp__570426996 = 0;
              colontmp__570426995 = addInt(i_570425794, 1);
              colontmp__570426996 = (active_p1).length;
              var i_570426997 = colontmp__570426995;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570426997 < colontmp__570426996)) break Label6;
                    j_570425802 = i_570426997;
                    var count_570425803 = counts_p0[chckIndx(active_p1[chckIndx(i_570425794, 0, (active_p1).length - 1)], 0, (counts_p0).length - 1)][chckIndx(active_p1[chckIndx(j_570425802, 0, (active_p1).length - 1)], 0, (counts_p0[chckIndx(active_p1[chckIndx(i_570425794, 0, (active_p1).length - 1)], 0, (counts_p0).length - 1)]).length - 1)];
                    result_570425783.pairs = addInt(result_570425783.pairs, 1);
                    result_570425783.total = addInt(result_570425783.total, count_570425803);
                    if ((count_570425803 < low_570425784)) {
                    result_570425783.below = addInt(result_570425783.below, 1);
                    }
                    else {
                    if ((high_570425785 < count_570425803)) {
                    result_570425783.above = addInt(result_570425783.above, 1);
                    }
                    else {
                    result_570425783.inside = addInt(result_570425783.inside, 1);
                    }
                    }
                    i_570426997 = addInt(i_570426997, 1);
                  }
              };
            };
            i_570427000 = addInt(i_570427000, 1);
          }
      };
    };
    if ((0 < result_570425783.pairs)) {
    result_570425783.average = (result_570425783.total / result_570425783.pairs);
    }


  return result_570425783;

}

function nsuformatBiggestFloat(f_p0, format_p1, precision_p2, decimalSep_p3) {
  var result_721422505 = [];

    var precision_721422506 = precision_p2;
    if ((precision_721422506 == (-1))) {
    precision_721422506 = 6;
    }

    var res_721422507 = null;
    switch (format_p1) {
    case 0:
      res_721422507 = f_p0.toString();
      break;
    case 1:
      res_721422507 = f_p0.toFixed(precision_721422506);
      break;
    case 2:
      res_721422507 = f_p0.toExponential(precision_721422506);
      break;
    }
    result_721422505 = nimCopy(null, cstrToNimstr(res_721422507), NTI33554449);
    if (((1.0 / f_p0) == -Infinity)) {
    result_721422505 = nimCopy(null, ([45]).concat(cstrToNimstr(res_721422507)), NTI33554449);
    }

    Label1: {
      var i_721422512 = 0;
      var colontmp__570427003 = 0;
      colontmp__570427003 = (result_721422505).length;
      var i_570427004 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427004 < colontmp__570427003)) break Label3;
            i_721422512 = i_570427004;
            if ((ConstSet2[result_721422505[chckIndx(i_721422512, 0, (result_721422505).length - 1)]] != undefined)) {
            result_721422505[chckIndx(i_721422512, 0, (result_721422505).length - 1)] = decimalSep_p3;
            }

            i_570427004 = addInt(i_570427004, 1);
          }
      };
    };

  return result_721422505;

}

function nsuformatFloat(f_p0, format_p1, precision_p2, decimalSep_p3) {
  var result_721422538 = [];

    result_721422538 = nimCopy(null, nsuformatBiggestFloat(f_p0, format_p1, precision_p2, decimalSep_p3), NTI33554449);

  return result_721422538;

}

function renderAutoStatus__main_u1111(counts_p0) {
  var result_570426457 = [];

    var active_570426458 = activeIndices__main_u197();
    var stats_570426459 = computePairStats__main_u436(counts_p0, active_570426458);
    var noun_570426460 = plural__main_u103(state_570425401[0].autoSteps, [103,97,109,101], [103,97,109,101,115]);
    var average_570426461 = nsuformatFloat(stats_570426459.average, 1, 1, 46);
    result_570426457.push.apply(result_570426457, ([60,115,112,97,110,62]).concat(HEX24__systemZdollars_u14(state_570425401[0].autoSteps),[32,97,117,116,111,32],noun_570426460,[60,47,115,112,97,110,62]));;
    result_570426457.push.apply(result_570426457, ([60,115,112,97,110,62]).concat(average_570426461,[32,97,118,101,114,97,103,101,32,112,97,105,114,105,110,103,32,103,97,109,101,115,60,47,115,112,97,110,62]));;
    result_570426457.push.apply(result_570426457, ([60,115,112,97,110,62]).concat(HEX24__systemZdollars_u14(stats_570426459.inside),[47],HEX24__systemZdollars_u14(stats_570426459.pairs)));;
    result_570426457.push.apply(result_570426457, [32,112,97,105,114,115,32,105,110,32,114,97,110,103,101,60,47,115,112,97,110,62]);;

  return result_570426457;

}

function maxCount__main_u405(counts_p0) {
  var result_570425751 = 0;

    Label1: {
      var i_570425756 = 0;
      var i_570427022 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427022 < 15)) break Label3;
            i_570425756 = i_570427022;
            Label4: {
              var j_570425761 = 0;
              var i_570427020 = 0;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570427020 < 15)) break Label6;
                    j_570425761 = i_570427020;
                    if (!((i_570425756 == j_570425761))) {
                    result_570425751 = nimMax(result_570425751, counts_p0[chckIndx(i_570425756, 0, (counts_p0).length - 1)][chckIndx(j_570425761, 0, (counts_p0[chckIndx(i_570425756, 0, (counts_p0).length - 1)]).length - 1)]);
                    }

                    i_570427020 = addInt(i_570427020, 1);
                  }
              };
            };
            i_570427022 = addInt(i_570427022, 1);
          }
      };
    };

  return result_570425751;

}

function renderColumnLabel__main_u1118(index_p0) {
    var Temporary1;

  var result_570426464 = [];

    var x_570426465 = addInt(addInt(170, mulInt(index_p0, 32)), 16);
    var y_570426466 = 122;
    if (state_570425401[0].policies[chckIndx(index_p0, 0, (state_570425401[0].policies).length - 1)].active) {
    Temporary1 = [104,101,97,116,45,108,97,98,101,108];
    }
    else {
    Temporary1 = [104,101,97,116,45,108,97,98,101,108,32,101,120,99,108,117,100,101,100];
    }

    var labelClass_570426467 = nimCopy(null, Temporary1, NTI33554449);
    result_570426464.push.apply(result_570426464, ([60,116,101,120,116,32,99,108,97,115,115,61,34]).concat(labelClass_570426467));;
    result_570426464.push.apply(result_570426464, ([34,32,120,61,34]).concat(HEX24__systemZdollars_u14(x_570426465),[34,32,121,61,34],HEX24__systemZdollars_u14(y_570426466)));;
    result_570426464.push.apply(result_570426464, [34,32,116,101,120,116,45,97,110,99,104,111,114,61,34,115,116,97,114,116,34,32,116,114,97,110,115,102,111,114,109,61,34,114,111,116,97,116,101,40,45,52,53,32]);;
    result_570426464.push.apply(result_570426464, (HEX24__systemZdollars_u14(x_570426465)).concat([32],HEX24__systemZdollars_u14(y_570426466),[41,34,62]));;
    result_570426464.push.apply(result_570426464, escapeHtml__main_u94(state_570425401[0].policies[chckIndx(index_p0, 0, (state_570425401[0].policies).length - 1)].label));;
    result_570426464.push.apply(result_570426464, [60,47,116,101,120,116,62,10]);;

  return result_570426464;

}

function renderRowLabel__main_u1124(index_p0) {
    var Temporary1;

  var result_570426470 = [];

    var x_570426471 = 162;
    var y_570426472 = addInt(addInt(addInt(130, mulInt(index_p0, 32)), 16), 4);
    if (state_570425401[0].policies[chckIndx(index_p0, 0, (state_570425401[0].policies).length - 1)].active) {
    Temporary1 = [104,101,97,116,45,108,97,98,101,108];
    }
    else {
    Temporary1 = [104,101,97,116,45,108,97,98,101,108,32,101,120,99,108,117,100,101,100];
    }

    var labelClass_570426473 = nimCopy(null, Temporary1, NTI33554449);
    result_570426470.push.apply(result_570426470, ([60,116,101,120,116,32,99,108,97,115,115,61,34]).concat(labelClass_570426473));;
    result_570426470.push.apply(result_570426470, ([34,32,120,61,34]).concat(HEX24__systemZdollars_u14(x_570426471),[34,32,121,61,34],HEX24__systemZdollars_u14(y_570426472)));;
    result_570426470.push.apply(result_570426470, [34,32,116,101,120,116,45,97,110,99,104,111,114,61,34,101,110,100,34,62]);;
    result_570426470.push.apply(result_570426470, escapeHtml__main_u94(state_570425401[0].policies[chckIndx(index_p0, 0, (state_570425401[0].policies).length - 1)].label));;
    result_570426470.push.apply(result_570426470, [60,47,116,101,120,116,62,10]);;

  return result_570426470;

}

function heatRatio__main_u1028(count_p0, highest_p1) {
  var result_570426375 = 0.0;

  BeforeRet: {
    if (((highest_p1 <= 0) || (count_p0 <= 0))) {
    result_570426375 = 0.0;
    break BeforeRet;
    }

    result_570426375 = (count_p0 / highest_p1);
    if ((result_570426375 < 0.0)) {
    result_570426375 = 0.0;
    }
    else {
    if ((1.0 < result_570426375)) {
    result_570426375 = 1.0;
    }
    }
  };

  return result_570426375;

}

function heatColor__main_u1032(count_p0, highest_p1) {
  var result_570426379 = [];

  BeforeRet: {
    if ((count_p0 <= 0)) {
    result_570426379 = nimCopy(null, [114,103,98,40,50,53,53,44,50,53,53,44,50,53,53,41], NTI33554449);
    break BeforeRet;
    }

    var ratio_570426380 = heatRatio__main_u1028(count_p0, highest_p1);
    var colors_570426381 = new Int32Array(3);
    Label1: {
      var i_570426394 = 0;
      var i_570427025 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427025 < 3)) break Label3;
            i_570426394 = i_570427025;
            colors_570426381[chckIndx(i_570426394, 0, (colors_570426381).length - 1)] = ((((HeatLowColor_570425364[chckIndx(i_570426394, 0, (HeatLowColor_570425364).length - 1)] + (subInt(HeatHighColor_570425365[chckIndx(i_570426394, 0, (HeatHighColor_570425365).length - 1)], HeatLowColor_570425364[chckIndx(i_570426394, 0, (HeatLowColor_570425364).length - 1)]) * ratio_570426380)) + 0.5)) | 0);
            i_570427025 = addInt(i_570427025, 1);
          }
      };
    };
    result_570426379 = nimCopy(null, ([114,103,98,40]).concat(HEX24__systemZdollars_u14(colors_570426381[chckIndx(0, 0, (colors_570426381).length - 1)]),[44],HEX24__systemZdollars_u14(colors_570426381[chckIndx(1, 0, (colors_570426381).length - 1)]),[44],HEX24__systemZdollars_u14(colors_570426381[chckIndx(2, 0, (colors_570426381).length - 1)]),[41]), NTI33554449);
  };

  return result_570426379;

}

function countTitle__main_u1071(row_p0, column_p1, count_p2) {
  var result_570426419 = [];

    var noun_570426420 = plural__main_u103(count_p2, [103,97,109,101], [103,97,109,101,115]);
    result_570426419 = nimCopy(null, (state_570425401[0].policies[chckIndx(row_p0, 0, (state_570425401[0].policies).length - 1)].label).concat([32,118,115,32],state_570425401[0].policies[chckIndx(column_p1, 0, (state_570425401[0].policies).length - 1)].label,[58,32],HEX24__systemZdollars_u14(count_p2),[32],noun_570426420), NTI33554449);

  return result_570426419;

}

function heatTextColor__main_u1067(count_p0, highest_p1) {
    var Temporary1;

  var result_570426414 = [];

    if ((0.55 <= heatRatio__main_u1028(count_p0, highest_p1))) {
    Temporary1 = [35,102,102,102,102,102,102];
    }
    else {
    Temporary1 = [35,49,49,49,49,49,49];
    }

    result_570426414 = nimCopy(null, Temporary1, NTI33554449);

  return result_570426414;

}

function renderHeatCell__main_u1130(counts_p0, row_p1, column_p2, highest_p3) {
  var result_570426479 = [];

  BeforeRet: {
    if ((row_p1 == column_p2)) {
    break BeforeRet;
    }

    var count_570426480 = counts_p0[chckIndx(row_p1, 0, (counts_p0).length - 1)][chckIndx(column_p2, 0, (counts_p0[chckIndx(row_p1, 0, (counts_p0).length - 1)]).length - 1)];
    var x_570426481 = addInt(170, mulInt(column_p2, 32));
    var y_570426482 = addInt(130, mulInt(row_p1, 32));
    var textX_570426483 = addInt(x_570426481, 16);
    var textY_570426484 = addInt(addInt(y_570426482, 16), 4);
    result_570426479.push.apply(result_570426479, ([60,114,101,99,116,32,99,108,97,115,115,61,34,104,101,97,116,45,99,101,108,108,34,32,120,61,34]).concat(HEX24__systemZdollars_u14(x_570426481)));;
    result_570426479.push.apply(result_570426479, ([34,32,121,61,34]).concat(HEX24__systemZdollars_u14(y_570426482),[34,32,119,105,100,116,104,61,34,51,50]));;
    result_570426479.push.apply(result_570426479, [34,32,104,101,105,103,104,116,61,34,51,50]);;
    result_570426479.push.apply(result_570426479, ([34,32,102,105,108,108,61,34]).concat(heatColor__main_u1032(count_570426480, highest_p3)));;
    result_570426479.push.apply(result_570426479, [34,62,60,116,105,116,108,101,62]);;
    result_570426479.push.apply(result_570426479, escapeHtml__main_u94(countTitle__main_u1071(row_p1, column_p2, count_570426480)));;
    result_570426479.push.apply(result_570426479, [60,47,116,105,116,108,101,62,60,47,114,101,99,116,62,10]);;
    if ((0 < count_570426480)) {
    result_570426479.push.apply(result_570426479, ([60,116,101,120,116,32,99,108,97,115,115,61,34,104,101,97,116,45,114,97,116,101,34,32,120,61,34]).concat(HEX24__systemZdollars_u14(textX_570426483)));;
    result_570426479.push.apply(result_570426479, ([34,32,121,61,34]).concat(HEX24__systemZdollars_u14(textY_570426484)));;
    result_570426479.push.apply(result_570426479, [34,32,116,101,120,116,45,97,110,99,104,111,114,61,34,109,105,100,100,108,101,34,32,102,105,108,108,61,34]);;
    result_570426479.push.apply(result_570426479, heatTextColor__main_u1067(count_570426480, highest_p3));;
    result_570426479.push.apply(result_570426479, ([34,62]).concat(HEX24__systemZdollars_u14(count_570426480),[60,47,116,101,120,116,62,10]));;
    }

  };

  return result_570426479;

}

function renderChart__main_u1141(counts_p0) {
  var result_570426487 = [];

    var gridWidth_570426488 = 480;
    var width_570426489 = addInt(addInt(170, gridWidth_570426488), 170);
    var height_570426490 = 622;
    var highest_570426491 = maxCount__main_u405(counts_p0);
    result_570426487.push.apply(result_570426487, [60,100,105,118,32,99,108,97,115,115,61,34,104,101,97,116,45,119,114,97,112,34,62,10]);;
    result_570426487.push.apply(result_570426487, ([60,115,118,103,32,99,108,97,115,115,61,34,104,101,97,116,109,97,112,45,115,118,103,34,32,119,105,100,116,104,61,34]).concat(HEX24__systemZdollars_u14(width_570426489)));;
    result_570426487.push.apply(result_570426487, ([34,32,104,101,105,103,104,116,61,34]).concat(HEX24__systemZdollars_u14(height_570426490),[34,32,118,105,101,119,66,111,120,61,34,48,32,48,32]));;
    result_570426487.push.apply(result_570426487, (HEX24__systemZdollars_u14(width_570426489)).concat([32],HEX24__systemZdollars_u14(height_570426490)));;
    result_570426487.push.apply(result_570426487, [34,32,114,111,108,101,61,34,105,109,103,34,32,97,114,105,97,45,108,97,98,101,108,61,34,80,111,108,105,99,121,32,109,97,116,99,104,117,112,32,99,111,117,110,116,32,104,101,97,116,32,109,97,112,34,62,10]);;
    Label1: {
      var i_570426496 = 0;
      var i_570427007 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427007 < 15)) break Label3;
            i_570426496 = i_570427007;
            result_570426487.push.apply(result_570426487, renderColumnLabel__main_u1118(i_570426496));;
            i_570427007 = addInt(i_570427007, 1);
          }
      };
    };
    Label4: {
      var i_570426501 = 0;
      var i_570427010 = 0;
      Label5: {
          Label6: while (true) {
          if (!(i_570427010 < 15)) break Label6;
            i_570426501 = i_570427010;
            result_570426487.push.apply(result_570426487, renderRowLabel__main_u1124(i_570426501));;
            i_570427010 = addInt(i_570427010, 1);
          }
      };
    };
    Label7: {
      var i_570426506 = 0;
      var i_570427016 = 0;
      Label8: {
          Label9: while (true) {
          if (!(i_570427016 < 15)) break Label9;
            i_570426506 = i_570427016;
            Label10: {
              var j_570426511 = 0;
              var i_570427014 = 0;
              Label11: {
                  Label12: while (true) {
                  if (!(i_570427014 < 15)) break Label12;
                    j_570426511 = i_570427014;
                    result_570426487.push.apply(result_570426487, renderHeatCell__main_u1130(counts_p0, i_570426506, j_570426511, highest_570426491));;
                    i_570427014 = addInt(i_570427014, 1);
                  }
              };
            };
            i_570427016 = addInt(i_570427016, 1);
          }
      };
    };
    result_570426487.push.apply(result_570426487, [60,47,115,118,103,62,10,60,47,100,105,118,62,10]);;

  return result_570426487;

}

function render__main_u1168() {
    var Temporary1;
    var Temporary2;
    var Temporary3;

    var counts_570426824 = computeCounts__main_u377();
    var includedGames_570426825 = activeGameCount__main_u315();
    var playEnabled_570426826 = canPlay__main_u1169();
    var removeEnabled_570426827 = canRemove__main_u1171(includedGames_570426825);
    var autoEnabled_570426828 = canAutoEqualize__main_u1395();
    if (playEnabled_570426826) {
    Temporary1 = [102,97,108,115,101];
    }
    else {
    Temporary1 = [116,114,117,101];
    }

    var playDisabledText_570426829 = nimCopy(null, Temporary1, NTI33554449);
    if (removeEnabled_570426827) {
    Temporary2 = [102,97,108,115,101];
    }
    else {
    Temporary2 = [116,114,117,101];
    }

    var removeDisabledText_570426830 = nimCopy(null, Temporary2, NTI33554449);
    if (autoEnabled_570426828) {
    Temporary3 = [102,97,108,115,101];
    }
    else {
    Temporary3 = [116,114,117,101];
    }

    var autoDisabledText_570426831 = nimCopy(null, Temporary3, NTI33554449);
    document.getElementById("policy-panel").innerHTML = toJSStr(renderPolicyTable__main_u1085(counts_570426824));
    document.getElementById("game-value").textContent = toJSStr(HEX24__systemZdollars_u14(state_570425401[0].sliderGames));
    document.getElementById("play-button").textContent = toJSStr(playButtonText__main_u1077());
    document.getElementById("remove-button").textContent = toJSStr(removeButtonText__main_u1080());
    document.getElementById("auto-target-value").textContent = toJSStr(HEX24__systemZdollars_u14(state_570425401[0].targetPairGames));
    document.getElementById("auto-button").textContent = toJSStr(autoButtonText__main_u1083());
    document.getElementById("play-button").disabled = !(playEnabled_570426826);
    document.getElementById("remove-button").disabled = !(removeEnabled_570426827);
    document.getElementById("auto-button").disabled = !(autoEnabled_570426828);
    document.getElementById("play-button").setAttribute("aria-disabled", toJSStr(playDisabledText_570426829));
    document.getElementById("remove-button").setAttribute("aria-disabled", toJSStr(removeDisabledText_570426830));
    document.getElementById("auto-button").setAttribute("aria-disabled", toJSStr(autoDisabledText_570426831));
    document.getElementById("status-line").innerHTML = toJSStr(renderStatus__main_u1098(includedGames_570426825));
    document.getElementById("auto-status-line").innerHTML = toJSStr(renderAutoStatus__main_u1111(counts_570426824));
    document.getElementById("chart").innerHTML = toJSStr(renderChart__main_u1141(counts_570426824));


}

function updateSlider__main_u1459() {
    state_570425401[0].sliderGames = clampInt__main_u98(parseInt(document.getElementById('game-slider').value, 10), 1, 100);
    state_570425401[0].message = nimCopy(null, [], NTI33554449);
    render__main_u1168();


}

function updateAutoTarget__main_u1460() {
    state_570425401[0].targetPairGames = clampInt__main_u98(parseInt(document.getElementById('auto-target-slider').value, 10), 10, 1000);
    if (!(state_570425401[0].autoRunning)) {
    state_570425401[0].message = nimCopy(null, [], NTI33554449);
    }

    render__main_u1168();


}

function updateAllocation__main_u1461() {
    var value_570426806 = cstrToNimstr((document.querySelector('input[name="allocation-type"]:checked') || {}).value ||
  'random'
);
    switch (toJSStr(value_570426806)) {
    case "policies":
      state_570425401[0].allocationType = 1;
      break;
    case "pairings":
      state_570425401[0].allocationType = 2;
      break;
    default:
      state_570425401[0].allocationType = 0;
      break;
    }
    state_570425401[0].message = nimCopy(null, [], NTI33554449);
    render__main_u1168();


}

function randomIndex__main_u530(limit_p0) {
  var result_570425876 = 0;

  BeforeRet: {
    if ((limit_p0 <= 0)) {
    result_570425876 = 0;
    break BeforeRet;
    }

    result_570425876 = (((Math.random() * limit_p0)) | 0);
    if ((limit_p0 <= result_570425876)) {
    result_570425876 = subInt(limit_p0, 1);
    }

  };

  return result_570425876;

}

function shuffle__main_u533(values_p0, values_p0_Idx) {
  BeforeRet: {
    if (((values_p0[values_p0_Idx]).length <= 1)) {
    break BeforeRet;
    }

    var i_570425885 = subInt((values_p0[values_p0_Idx]).length, 1);
    Label1: {
        Label2: while (true) {
        if (!(0 < i_570425885)) break Label2;
          var j_570425886 = randomIndex__main_u530(addInt(i_570425885, 1));
          var HEX3Atmp_570427035 = values_p0[values_p0_Idx][chckIndx(i_570425885, 0, (values_p0[values_p0_Idx]).length - 1)];
          values_p0[values_p0_Idx][chckIndx(i_570425885, 0, (values_p0[values_p0_Idx]).length - 1)] = values_p0[values_p0_Idx][chckIndx(j_570425886, 0, (values_p0[values_p0_Idx]).length - 1)];
          values_p0[values_p0_Idx][chckIndx(j_570425886, 0, (values_p0[values_p0_Idx]).length - 1)] = HEX3Atmp_570427035;
          i_570425885 = subInt(i_570425885, 1);
        }
    };
  };


}

function randomSeats__main_u552(active_p0) {
  var result_570425898 = [[]];

    Label1: {
      var index_570425911 = 0;
      var i_570427032 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427032 < (active_p0).length)) break Label3;
            index_570425911 = active_p0[chckIndx(i_570427032, 0, (active_p0).length - 1)];
            result_570425898[0].push(index_570425911);;
            i_570427032 += 1;
          }
      };
    };
    shuffle__main_u533(result_570425898, 0);
    if (result_570425898[0].length < 8) { for (var i = result_570425898[0].length ; i < 8 ; ++i) result_570425898[0].push(0); }
               else { result_570425898[0].length = 8; };

  return result_570425898[0];

}

function newSeq__main_u644(len_p0) {
  var result_570425992 = [];

    result_570425992 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_570425992[i] = ({index: 0, games: 0, tie: 0.0}); }
  return result_570425992;

}

function HEX2A__pureZalgorithm_u8(x_p0, order_p1) {
  var result_704643083 = 0;

    var y_704643088 = subInt(order_p1, 1);
    result_704643083 = subInt((x_p0 ^ y_704643088), y_704643088);

  return result_704643083;

}

function mergeAlt__main_u690(a_p0, b_p1, lo_p2, m_p3, hi_p4, cmp_p5, order_p6) {
  BeforeRet: {
    if ((HEX2A__pureZalgorithm_u8(cmp_p5(a_p0[chckIndx(m_p3, 0, (a_p0).length - 1)], a_p0[chckIndx(addInt(m_p3, 1), 0, (a_p0).length - 1)]), order_p6) <= 0)) {
    break BeforeRet;
    }

    var j_570426045 = lo_p2;
    if (!((j_570426045 <= m_p3))) {
    failedAssertImpl__stdZassertions_u84([97,108,103,111,114,105,116,104,109,46,110,105,109,40,51,51,56,44,32,51,41,32,96,106,32,60,61,32,109,96,32]);
    }

    var bb_570426051 = 0;
    Label1: {
        Label2: while (true) {
        if (!(j_570426045 <= m_p3)) break Label2;
          b_p1[chckIndx(bb_570426051, 0, (b_p1).length - 1)] = nimCopy(b_p1[chckIndx(bb_570426051, 0, (b_p1).length - 1)], a_p0[chckIndx(j_570426045, 0, (a_p0).length - 1)], NTI570425374);
          bb_570426051 = addInt(bb_570426051, 1);
          j_570426045 = addInt(j_570426045, 1);
        }
    };
    var i_570426062 = 0;
    var k_570426063 = lo_p2;
    Label3: {
        Label4: while (true) {
        if (!((k_570426063 < j_570426045) && (j_570426045 <= hi_p4))) break Label4;
          if ((HEX2A__pureZalgorithm_u8(cmp_p5(b_p1[chckIndx(i_570426062, 0, (b_p1).length - 1)], a_p0[chckIndx(j_570426045, 0, (a_p0).length - 1)]), order_p6) <= 0)) {
          a_p0[chckIndx(k_570426063, 0, (a_p0).length - 1)] = nimCopy(a_p0[chckIndx(k_570426063, 0, (a_p0).length - 1)], b_p1[chckIndx(i_570426062, 0, (b_p1).length - 1)], NTI570425374);
          i_570426062 = addInt(i_570426062, 1);
          }
          else {
            a_p0[chckIndx(k_570426063, 0, (a_p0).length - 1)] = nimCopy(a_p0[chckIndx(k_570426063, 0, (a_p0).length - 1)], a_p0[chckIndx(j_570426045, 0, (a_p0).length - 1)], NTI570425374);
            j_570426045 = addInt(j_570426045, 1);
          }

          k_570426063 = addInt(k_570426063, 1);
        }
    };
    Label5: {
        Label6: while (true) {
        if (!(k_570426063 < j_570426045)) break Label6;
          a_p0[chckIndx(k_570426063, 0, (a_p0).length - 1)] = nimCopy(a_p0[chckIndx(k_570426063, 0, (a_p0).length - 1)], b_p1[chckIndx(i_570426062, 0, (b_p1).length - 1)], NTI570425374);
          k_570426063 = addInt(k_570426063, 1);
          i_570426062 = addInt(i_570426062, 1);
        }
    };
  };


}

function sort__main_u615(a_p0, cmp_p1, order_p2) {
    var n_570425971 = (a_p0).length;
    var b_570426031 = newSeq__main_u644(chckRange(divInt(n_570425971, 2), 0, 2147483647));
    var s_570426032 = 1;
    Label1: {
        Label2: while (true) {
        if (!(s_570426032 < n_570425971)) break Label2;
          var m_570426033 = subInt(subInt(n_570425971, 1), s_570426032);
          Label3: {
              Label4: while (true) {
              if (!(0 <= m_570426033)) break Label4;
                mergeAlt__main_u690(a_p0, b_570426031, nimMax(addInt(subInt(m_570426033, s_570426032), 1), 0), m_570426033, addInt(m_570426033, s_570426032), cmp_p1, order_p2);
                m_570426033 = subInt(m_570426033, mulInt(s_570426032, 2));
              }
          };
          s_570426032 = mulInt(s_570426032, 2);
        }
    };


}

function cmp__system_u3610(x_p0, y_p1) {
  var result_33558046 = 0;

  BeforeRet: {
    if ((x_p0 == y_p1)) {
    result_33558046 = 0;
    break BeforeRet;
    }

    if ((x_p0 < y_p1)) {
    result_33558046 = (-1);
    break BeforeRet;
    }

    result_33558046 = 1;
    break BeforeRet;
  };

  return result_33558046;

}

function equalizedSeats__main_u592(active_p0) {
    var Temporary4;

function HEX3Aanonymous__main_u605(a_p0, b_p1) {
    var Temporary1;

  var result_570425952 = 0;

    if ((a_p0.games < b_p1.games)) {
    Temporary1 = (-1);
    }
    else {
    if ((b_p1.games < a_p0.games)) {
    Temporary1 = 1;
    }
    else {
    if ((a_p0.tie < b_p1.tie)) {
    Temporary1 = (-1);
    }
    else {
    if ((b_p1.tie < a_p0.tie)) {
    Temporary1 = 1;
    }
    else {
    Temporary1 = cmp__system_u3610(a_p0.index, b_p1.index);
    }
    }}}
    result_570425952 = Temporary1;

  return result_570425952;

}

  var result_570425938 = [];

    var counts_570425939 = computeCounts__main_u377();
    var ranks_570425940 = [];
    Label1: {
      var index_570425944 = 0;
      var i_570427037 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427037 < (active_p0).length)) break Label3;
            index_570425944 = active_p0[chckIndx(i_570427037, 0, (active_p0).length - 1)];
            ranks_570425940.push({index: index_570425944, games: policyGameCount__main_u418(counts_570425939, index_570425944), tie: Math.random()});;
            i_570427037 += 1;
          }
      };
    };
    Temporary4 = HEX3Aanonymous__main_u605.bind(null); Temporary4.ClP_0 = HEX3Aanonymous__main_u605; Temporary4.ClE_0 = null;
    sort__main_u615(ranks_570425940, Temporary4, 1);
    Label5: {
      var i_570426113 = 0;
      var i_570427040 = 0;
      Label6: {
          Label7: while (true) {
          if (!(i_570427040 < 8)) break Label7;
            i_570426113 = i_570427040;
            result_570425938.push(ranks_570425940[chckIndx(i_570426113, 0, (ranks_570425940).length - 1)].index);;
            i_570427040 = addInt(i_570427040, 1);
          }
      };
    };

  return result_570425938;

}

function minPairCount__main_u821(counts_p0, active_p1) {
  var result_570426168 = 0;

    var found_570426169 = false;
    Label1: {
      var i_570426177 = 0;
      var colontmp__570427056 = 0;
      colontmp__570427056 = (active_p1).length;
      var i_570427057 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427057 < colontmp__570427056)) break Label3;
            i_570426177 = i_570427057;
            Label4: {
              var j_570426185 = 0;
              var colontmp__570427052 = 0;
              var colontmp__570427053 = 0;
              colontmp__570427052 = addInt(i_570426177, 1);
              colontmp__570427053 = (active_p1).length;
              var i_570427054 = colontmp__570427052;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570427054 < colontmp__570427053)) break Label6;
                    j_570426185 = i_570427054;
                    var count_570426186 = counts_p0[chckIndx(active_p1[chckIndx(i_570426177, 0, (active_p1).length - 1)], 0, (counts_p0).length - 1)][chckIndx(active_p1[chckIndx(j_570426185, 0, (active_p1).length - 1)], 0, (counts_p0[chckIndx(active_p1[chckIndx(i_570426177, 0, (active_p1).length - 1)], 0, (counts_p0).length - 1)]).length - 1)];
                    if ((!(found_570426169) || (count_570426186 < result_570426168))) {
                    found_570426169 = true;
                    result_570426168 = count_570426186;
                    }

                    i_570427054 = addInt(i_570427054, 1);
                  }
              };
            };
            i_570427057 = addInt(i_570427057, 1);
          }
      };
    };

  return result_570426168;

}

function delete__main_u900(x_p0, x_p0_Idx, i_p1) {
    if (((x_p0[x_p0_Idx]).length - 1 < i_p1)) {
    raiseException({message: ([105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,58,32,39]).concat(HEX24__systemZdollars_u14(i_p1),[39,32,60,32,39],HEX24__systemZdollars_u14((x_p0[x_p0_Idx]).length),[39,32,102,97,105,108,101,100]), m_type: NTI134217749, parent: null, name: null, trace: [], up: null}, "IndexDefect");
    }

    x_p0[x_p0_Idx].splice(i_p1, 1);


}

function removeValue__main_u889(values_p0, values_p0_Idx, value_p1) {
  BeforeRet: {
    Label1: {
      var i_570426243 = 0;
      var colontmp__570427069 = 0;
      colontmp__570427069 = (values_p0[values_p0_Idx]).length;
      var i_570427070 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427070 < colontmp__570427069)) break Label3;
            i_570426243 = i_570427070;
            if ((values_p0[values_p0_Idx][chckIndx(i_570426243, 0, (values_p0[values_p0_Idx]).length - 1)] == value_p1)) {
            delete__main_u900(values_p0, values_p0_Idx, chckRange(i_570426243, 0, 2147483647));
            break BeforeRet;
            }

            i_570427070 = addInt(i_570427070, 1);
          }
      };
    };
  };


}

function pairPenalty__main_u843(counts_p0, a_p1, b_p2, lowest_p3) {
  var result_570426192 = 0;

    var delta_570426193 = addInt(subInt(counts_p0[chckIndx(a_p1, 0, (counts_p0).length - 1)][chckIndx(b_p2, 0, (counts_p0[chckIndx(a_p1, 0, (counts_p0).length - 1)]).length - 1)], lowest_p3), 1);
    result_570426192 = mulInt(delta_570426193, delta_570426193);

  return result_570426192;

}

function addPairScore__main_u875(counts_p0, seats_p1, index_p2, lowest_p3) {
  var result_570426224 = 0;

    Label1: {
      var seat_570426228 = 0;
      var i_570427078 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427078 < (seats_p1).length)) break Label3;
            seat_570426228 = seats_p1[chckIndx(i_570427078, 0, (seats_p1).length - 1)];
            result_570426224 = addInt(result_570426224, pairPenalty__main_u843(counts_p0, seat_570426228, index_p2, lowest_p3));
            i_570427078 += 1;
          }
      };
    };

  return result_570426224;

}

function sampledPairingSeats__main_u928(counts_p0, active_p1, lowest_p2) {
          var Temporary9;

function HEX3Aanonymous__main_u979(a_p0, b_p1) {
    var Temporary1;

  var result_570426326 = 0;

    if ((a_p0.games < b_p1.games)) {
    Temporary1 = (-1);
    }
    else {
    if ((b_p1.games < a_p0.games)) {
    Temporary1 = 1;
    }
    else {
    if ((a_p0.tie < b_p1.tie)) {
    Temporary1 = (-1);
    }
    else {
    if ((b_p1.tie < a_p0.tie)) {
    Temporary1 = 1;
    }
    else {
    Temporary1 = cmp__system_u3610(a_p0.index, b_p1.index);
    }
    }}}
    result_570426326 = Temporary1;

  return result_570426326;

}

  var result_570426276 = [];

    var remaining_570426277 = [[]];
    Label1: {
      var index_570426281 = 0;
      var i_570427060 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427060 < (active_p1).length)) break Label3;
            index_570426281 = active_p1[chckIndx(i_570427060, 0, (active_p1).length - 1)];
            remaining_570426277[0].push(index_570426281);;
            i_570427060 += 1;
          }
      };
    };
    result_570426276.push(remaining_570426277[0][chckIndx(randomIndex__main_u530((remaining_570426277[0]).length), 0, (remaining_570426277[0]).length - 1)]);;
    removeValue__main_u889(remaining_570426277, 0, result_570426276[chckIndx(0, 0, (result_570426276).length - 1)]);
    Label4: {
        Label5: while (true) {
        if (!((result_570426276).length < 8)) break Label5;
          var ranks_570426296 = [];
          Label6: {
            var index_570426318 = 0;
            var i_570427065 = 0;
            var L_570427066 = (remaining_570426277[0]).length;
            Label7: {
                Label8: while (true) {
                if (!(i_570427065 < L_570427066)) break Label8;
                  index_570426318 = remaining_570426277[0][chckIndx(i_570427065, 0, (remaining_570426277[0]).length - 1)];
                  ranks_570426296.push({index: index_570426318, games: addPairScore__main_u875(counts_p0, result_570426276, index_570426318, lowest_p2), tie: Math.random()});;
                  i_570427065 += 1;
                  if (!(((remaining_570426277[0]).length == L_570427066))) {
                  failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                  }

                }
            };
          };
          Temporary9 = HEX3Aanonymous__main_u979.bind(null); Temporary9.ClP_0 = HEX3Aanonymous__main_u979; Temporary9.ClE_0 = null;
          sort__main_u615(ranks_570426296, Temporary9, 1);
          var window_570426345 = nimMin(4, (ranks_570426296).length);
          var chosen_570426346 = ranks_570426296[chckIndx(randomIndex__main_u530(window_570426345), 0, (ranks_570426296).length - 1)].index;
          result_570426276.push(chosen_570426346);;
          removeValue__main_u889(remaining_570426277, 0, chosen_570426346);
        }
    };

  return result_570426276;

}

function pairScore__main_u850(counts_p0, seats_p1, lowest_p2) {
  var result_570426198 = 0;

    Label1: {
      var i_570426206 = 0;
      var colontmp__570427086 = 0;
      colontmp__570427086 = (seats_p1).length;
      var i_570427087 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427087 < colontmp__570427086)) break Label3;
            i_570426206 = i_570427087;
            Label4: {
              var j_570426214 = 0;
              var colontmp__570427082 = 0;
              var colontmp__570427083 = 0;
              colontmp__570427082 = addInt(i_570426206, 1);
              colontmp__570427083 = (seats_p1).length;
              var i_570427084 = colontmp__570427082;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570427084 < colontmp__570427083)) break Label6;
                    j_570426214 = i_570427084;
                    result_570426198 = addInt(result_570426198, pairPenalty__main_u843(counts_p0, seats_p1[chckIndx(i_570426206, 0, (seats_p1).length - 1)], seats_p1[chckIndx(j_570426214, 0, (seats_p1).length - 1)], lowest_p2));
                    i_570427084 = addInt(i_570427084, 1);
                  }
              };
            };
            i_570427087 = addInt(i_570427087, 1);
          }
      };
    };

  return result_570426198;

}

function pairizedSeats__main_u1007(active_p0) {
            var Temporary4;

  var result_570426353 = [];

    var counts_570426354 = computeCounts__main_u377();
    var lowest_570426355 = minPairCount__main_u821(counts_570426354, active_p0);
    var bestFound_570426356 = false;
    var bestScore_570426357 = 0;
    var tieCount_570426358 = 0;
    var bestSeats_570426359 = [];
    Label1: {
      var i_570426364 = 0;
      var i_570427048 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427048 < 192)) break Label3;
            i_570426364 = i_570427048;
            if ((modInt(i_570426364, 5) == 0)) {
            Temporary4 = randomSeats__main_u552(active_p0);
            }
            else {
            Temporary4 = sampledPairingSeats__main_u928(counts_570426354, active_p0, lowest_570426355);
            }

            var seats_570426365 = nimCopy(null, Temporary4, NTI570425666);
            var score_570426366 = pairScore__main_u850(counts_570426354, seats_570426365, lowest_570426355);
            if ((!(bestFound_570426356) || (score_570426366 < bestScore_570426357))) {
            bestFound_570426356 = true;
            bestScore_570426357 = score_570426366;
            tieCount_570426358 = 1;
            bestSeats_570426359 = nimCopy(null, seats_570426365, NTI570425666);
            }
            else {
            if ((score_570426366 == bestScore_570426357)) {
            tieCount_570426358 = addInt(tieCount_570426358, 1);
            if ((randomIndex__main_u530(tieCount_570426358) == 0)) {
            bestSeats_570426359 = nimCopy(null, seats_570426365, NTI570425666);
            }

            }
            }
            i_570427048 = addInt(i_570427048, 1);
          }
      };
    };
    result_570426353 = nimCopy(null, bestSeats_570426359, NTI570425949);

  return result_570426353;

}

function recordGame__main_u1174(seats_p0) {
    var game_570426520 = ({seats: new Int32Array(8)});
    Label1: {
      var i_570426525 = 0;
      var i_570427090 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427090 < 8)) break Label3;
            i_570426525 = i_570427090;
            game_570426520.seats[chckIndx(i_570426525, 0, (game_570426520.seats).length - 1)] = seats_p0[chckIndx(i_570426525, 0, (seats_p0).length - 1)];
            i_570427090 = addInt(i_570427090, 1);
          }
      };
    };
    var Temporary4 = nimCopy(null, game_570426520, NTI570425373);
    state_570425401[0].games.push(Temporary4);;


}

function playOneGame__main_u1202() {
    var Temporary1;

  var result_570426547 = false;

  BeforeRet: {
    var active_570426548 = activeIndices__main_u197();
    if (((active_570426548).length < 8)) {
    state_570425401[0].message = nimCopy(null, [78,101,101,100,32,97,116,32,108,101,97,115,116,32,56,32,97,99,116,105,118,101,32,112,111,108,105,99,105,101,115,46], NTI33554449);
    result_570426547 = false;
    break BeforeRet;
    }

    switch (state_570425401[0].allocationType) {
    case 0:
      Temporary1 = randomSeats__main_u552(active_570426548);
      break;
    case 1:
      Temporary1 = equalizedSeats__main_u592(active_570426548);
      break;
    case 2:
      Temporary1 = pairizedSeats__main_u1007(active_570426548);
      break;
    }
    var seats_570426552 = nimCopy(null, Temporary1, NTI570425666);
    recordGame__main_u1174(seats_570426552);
    result_570426547 = true;
  };

  return result_570426547;

}

function allocationText__main_u250(allocationType_p0) {
    var Temporary1;

  var result_570425596 = [];

    switch (allocationType_p0) {
    case 0:
      Temporary1 = [114,97,110,100,111,109];
      break;
    case 1:
      Temporary1 = [112,111,108,105,99,121,45,101,113,117,97,108,105,122,101,100];
      break;
    case 2:
      Temporary1 = [112,97,105,114,105,110,103,45,101,113,117,97,108,105,122,101,100];
      break;
    }
    result_570425596 = nimCopy(null, Temporary1, NTI33554449);

  return result_570425596;

}

function playGames__main_u1370(gameCount_p0) {
    var count_570426716 = clampInt__main_u98(gameCount_p0, 1, 100);
    var played_570426717 = 0;
    Label1: {
      var i_570426722 = 0;
      var i_570427028 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427028 < count_570426716)) break Label3;
            i_570426722 = i_570427028;
            if (!(playOneGame__main_u1202())) {
            break Label1;
            }

            played_570426717 = addInt(played_570426717, 1);
            i_570427028 = addInt(i_570427028, 1);
          }
      };
    };
    if ((0 < played_570426717)) {
    var noun_570426728 = plural__main_u103(played_570426717, [103,97,109,101], [103,97,109,101,115]);
    state_570425401[0].message = nimCopy(null, ([80,108,97,121,101,100,32]).concat(HEX24__systemZdollars_u14(played_570426717),[32],noun_570426728,[32,119,105,116,104,32],allocationText__main_u250(state_570425401[0].allocationType),[32,97,108,108,111,99,97,116,105,111,110,46]), NTI33554449);
    }

    render__main_u1168();


}

function includedGameIndices__main_u1257() {
  var result_570426602 = [];

    Label1: {
      var i_570426643 = 0;
      var game_570426644 = ({seats: new Int32Array(8)});
      var i_570427095 = 0;
      var L_570427096 = (state_570425401[0].games).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570427095 < L_570427096)) break Label3;
            i_570426643 = i_570427095;
            game_570426644 = nimCopy(game_570426644, state_570425401[0].games[chckIndx(i_570427095, 0, (state_570425401[0].games).length - 1)], NTI570425373);
            if (gameIncluded__main_u253(game_570426644)) {
            result_570426602.push(i_570426643);;
            }

            i_570427095 += 1;
            if (!(((state_570425401[0].games).length == L_570427096))) {
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }

          }
      };
    };

  return result_570426602;

}

function policyRemovalScore__main_u1305(counts_p0, game_p1) {
  var result_570426652 = 0;

    Label1: {
      var index_570426657 = 0;
      var i_570427104 = 0;
      Label2: {
          Label3: while (true) {
          if (!true) break Label3;
            index_570426657 = game_p1.seats[chckIndx(i_570427104, 0, (game_p1.seats).length - 1)];
            result_570426652 = addInt(result_570426652, policyGameCount__main_u418(counts_p0, index_570426657));
            if ((7 <= i_570427104)) {
            break Label2;
            }

            i_570427104 += 1;
          }
      };
    };

  return result_570426652;

}

function highestPolicyGame__main_u1318(counts_p0) {
  var result_570426664 = 0;

    var bestFound_570426665 = false;
    var bestScore_570426666 = 0;
    var tieCount_570426667 = 0;
    Label1: {
      var index_570426673 = 0;
      var game_570426674 = ({seats: new Int32Array(8)});
      var i_570427100 = 0;
      var L_570427101 = (state_570425401[0].games).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570427100 < L_570427101)) break Label3;
            index_570426673 = i_570427100;
            game_570426674 = nimCopy(game_570426674, state_570425401[0].games[chckIndx(i_570427100, 0, (state_570425401[0].games).length - 1)], NTI570425373);
            Label4: {
              if (!(gameIncluded__main_u253(game_570426674))) {
              break Label4;
              }

              var score_570426675 = policyRemovalScore__main_u1305(counts_p0, game_570426674);
              if ((!(bestFound_570426665) || (bestScore_570426666 < score_570426675))) {
              bestFound_570426665 = true;
              bestScore_570426666 = score_570426675;
              tieCount_570426667 = 1;
              result_570426664 = index_570426673;
              }
              else {
              if ((score_570426675 == bestScore_570426666)) {
              tieCount_570426667 = addInt(tieCount_570426667, 1);
              if ((randomIndex__main_u530(tieCount_570426667) == 0)) {
              result_570426664 = index_570426673;
              }

              }
              }
            };
            i_570427100 += 1;
            if (!(((state_570425401[0].games).length == L_570427101))) {
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }

          }
      };
    };
    if (!(bestFound_570426665)) {
    result_570426664 = (-1);
    }


  return result_570426664;

}

function highestPairingGame__main_u1337(counts_p0) {
  var result_570426683 = 0;

    var active_570426684 = activeIndices__main_u197();
    var lowest_570426685 = minPairCount__main_u821(counts_p0, active_570426684);
    var bestFound_570426686 = false;
    var bestScore_570426687 = 0;
    var tieCount_570426688 = 0;
    Label1: {
      var index_570426694 = 0;
      var game_570426695 = ({seats: new Int32Array(8)});
      var i_570427108 = 0;
      var L_570427109 = (state_570425401[0].games).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570427108 < L_570427109)) break Label3;
            index_570426694 = i_570427108;
            game_570426695 = nimCopy(game_570426695, state_570425401[0].games[chckIndx(i_570427108, 0, (state_570425401[0].games).length - 1)], NTI570425373);
            Label4: {
              if (!(gameIncluded__main_u253(game_570426695))) {
              break Label4;
              }

              var score_570426696 = pairScore__main_u850(counts_p0, game_570426695.seats, lowest_570426685);
              if ((!(bestFound_570426686) || (bestScore_570426687 < score_570426696))) {
              bestFound_570426686 = true;
              bestScore_570426687 = score_570426696;
              tieCount_570426688 = 1;
              result_570426683 = index_570426694;
              }
              else {
              if ((score_570426696 == bestScore_570426687)) {
              tieCount_570426688 = addInt(tieCount_570426688, 1);
              if ((randomIndex__main_u530(tieCount_570426688) == 0)) {
              result_570426683 = index_570426694;
              }

              }
              }
            };
            i_570427108 += 1;
            if (!(((state_570425401[0].games).length == L_570427109))) {
            failedAssertImpl__stdZassertions_u84(makeNimstrLit("iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }

          }
      };
    };
    if (!(bestFound_570426686)) {
    result_570426683 = (-1);
    }


  return result_570426683;

}

function removalGameIndex__main_u1358() {
    var Temporary1;

  var result_570426703 = 0;

  BeforeRet: {
    switch (state_570425401[0].allocationType) {
    case 0:
      var candidates_570426704 = includedGameIndices__main_u1257();
      if (((candidates_570426704).length == 0)) {
      result_570426703 = (-1);
      break BeforeRet;
      }

      Temporary1 = candidates_570426704[chckIndx(randomIndex__main_u530((candidates_570426704).length), 0, (candidates_570426704).length - 1)];
      break;
    case 1:
      Temporary1 = highestPolicyGame__main_u1318(computeCounts__main_u377());
      break;
    case 2:
      Temporary1 = highestPairingGame__main_u1337(computeCounts__main_u377());
      break;
    }
    result_570426703 = Temporary1;
  };

  return result_570426703;

}

function delete__main_u1214(x_p0, x_p0_Idx, i_p1) {
    if (((x_p0[x_p0_Idx]).length - 1 < i_p1)) {
    raiseException({message: ([105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,58,32,39]).concat(HEX24__systemZdollars_u14(i_p1),[39,32,60,32,39],HEX24__systemZdollars_u14((x_p0[x_p0_Idx]).length),[39,32,102,97,105,108,101,100]), m_type: NTI134217749, parent: null, name: null, trace: [], up: null}, "IndexDefect");
    }

    x_p0[x_p0_Idx].splice(i_p1, 1);


}

function removeStoredGame__main_u1209(index_p0) {
  BeforeRet: {
    if (((index_p0 < 0) || ((state_570425401[0].games).length <= index_p0))) {
    break BeforeRet;
    }

    delete__main_u1214(state_570425401[0], "games", chckRange(index_p0, 0, 2147483647));
  };


}

function removeOneGame__main_u1367() {
  var result_570426712 = false;

  BeforeRet: {
    var index_570426713 = removalGameIndex__main_u1358();
    if ((index_570426713 < 0)) {
    result_570426712 = false;
    break BeforeRet;
    }

    removeStoredGame__main_u1209(index_570426713);
    result_570426712 = true;
  };

  return result_570426712;

}

function removeGames__main_u1385(gameCount_p0) {
    var count_570426731 = clampInt__main_u98(gameCount_p0, 1, 100);
    var removed_570426732 = 0;
    Label1: {
        Label2: while (true) {
        if (!(removed_570426732 < count_570426731)) break Label2;
          if (!(removeOneGame__main_u1367())) {
          break Label1;
          }

          removed_570426732 = addInt(removed_570426732, 1);
        }
    };
    if ((removed_570426732 == 0)) {
    state_570425401[0].message = nimCopy(null, [78,111,32,105,110,99,108,117,100,101,100,32,103,97,109,101,115,32,116,111,32,114,101,109,111,118,101,46], NTI33554449);
    }
    else {
      var noun_570426738 = plural__main_u103(removed_570426732, [103,97,109,101], [103,97,109,101,115]);
      state_570425401[0].message = nimCopy(null, ([82,101,109,111,118,101,100,32]).concat(HEX24__systemZdollars_u14(removed_570426732),[32],noun_570426738,[32,119,105,116,104,32],allocationText__main_u250(state_570425401[0].allocationType),[32,97,108,108,111,99,97,116,105,111,110,46]), NTI33554449);
    }

    render__main_u1168();


}

function stopAuto__main_u1399(message_p0) {
    if (!((state_570425401[0].autoTimerId == 0))) {
    clearInterval(state_570425401[0].autoTimerId);
    }

    state_570425401[0].autoRunning = false;
    state_570425401[0].autoTimerId = 0;
    state_570425401[0].message = nimCopy(null, message_p0, NTI33554449);


}

function autoTargetReached__main_u484(counts_p0) {
  var result_570425830 = false;

  BeforeRet: {
    var active_570425831 = activeIndices__main_u197();
    if (((active_570425831).length < 8)) {
    result_570425830 = false;
    break BeforeRet;
    }

    var stats_570425836 = computePairStats__main_u436(counts_p0, active_570425831);
    result_570425830 = (((0 < stats_570425836.pairs) && (stats_570425836.below == 0)) && (stats_570425836.above == 0));
  };

  return result_570425830;

}

function autoProgressMessage__main_u1397() {
  var result_570426742 = [];

    result_570426742 = nimCopy(null, ([65,117,116,111,45,101,113,117,97,108,105,122,105,110,103,32,116,111,119,97,114,100,32]).concat(HEX24__systemZdollars_u14(state_570425401[0].targetPairGames),[32,112,97,105,114,105,110,103,32,103,97,109,101,115,46]), NTI33554449);

  return result_570426742;

}

function autoTick__main_u1401() {
            var Temporary4;

  BeforeRet: {
    if (!(state_570425401[0].autoRunning)) {
    break BeforeRet;
    }

    if ((activeCount__main_u130() < 8)) {
    stopAuto__main_u1399([78,101,101,100,32,97,116,32,108,101,97,115,116,32,56,32,97,99,116,105,118,101,32,112,111,108,105,99,105,101,115,46]);
    render__main_u1168();
    break BeforeRet;
    }

    var counts_570426746 = computeCounts__main_u377();
    if (autoTargetReached__main_u484(counts_570426746)) {
    stopAuto__main_u1399([65,117,116,111,45,101,113,117,97,108,105,122,101,100,32,116,97,114,103,101,116,32,114,101,97,99,104,101,100,46]);
    render__main_u1168();
    break BeforeRet;
    }

    var active_570426747 = activeIndices__main_u197();
    var stats_570426748 = computePairStats__main_u436(counts_570426746, active_570426747);
    var removing_570426749 = (state_570425401[0].targetPairGames < stats_570426748.average);
    var batch_570426750 = clampInt__main_u98(state_570425401[0].sliderGames, 1, 100);
    var changed_570426751 = 0;
    Label1: {
      var i_570426756 = 0;
      var i_570427117 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570427117 < batch_570426750)) break Label3;
            i_570426756 = i_570427117;
            if (removing_570426749) {
            Temporary4 = removeOneGame__main_u1367();
            }
            else {
            Temporary4 = playOneGame__main_u1202();
            }

            var didChange_570426757 = Temporary4;
            if (!(didChange_570426757)) {
            break Label1;
            }

            changed_570426751 = addInt(changed_570426751, 1);
            if (autoTargetReached__main_u484(computeCounts__main_u377())) {
            break Label1;
            }

            i_570427117 = addInt(i_570427117, 1);
          }
      };
    };
    if ((changed_570426751 == 0)) {
    stopAuto__main_u1399([78,111,32,105,110,99,108,117,100,101,100,32,103,97,109,101,115,32,116,111,32,114,101,109,111,118,101,46]);
    render__main_u1168();
    break BeforeRet;
    }

    state_570425401[0].autoSteps = addInt(state_570425401[0].autoSteps, changed_570426751);
    if (autoTargetReached__main_u484(computeCounts__main_u377())) {
    stopAuto__main_u1399([65,117,116,111,45,101,113,117,97,108,105,122,101,100,32,116,97,114,103,101,116,32,114,101,97,99,104,101,100,46]);
    }
    else {
      state_570425401[0].message = nimCopy(null, autoProgressMessage__main_u1397(), NTI33554449);
    }

    render__main_u1168();
  };


}

function toggleAuto__main_u1423() {
    var Temporary1;

function HEX3Aanonymous__main_u1424() {
    autoTick__main_u1401();


}

  BeforeRet: {
    if (state_570425401[0].autoRunning) {
    stopAuto__main_u1399([65,117,116,111,45,101,113,117,97,108,105,122,101,114,32,115,116,111,112,112,101,100,46]);
    render__main_u1168();
    break BeforeRet;
    }

    if ((activeCount__main_u130() < 8)) {
    state_570425401[0].message = nimCopy(null, [78,101,101,100,32,97,116,32,108,101,97,115,116,32,56,32,97,99,116,105,118,101,32,112,111,108,105,99,105,101,115,46], NTI33554449);
    render__main_u1168();
    break BeforeRet;
    }

    state_570425401[0].autoSteps = 0;
    if (autoTargetReached__main_u484(computeCounts__main_u377())) {
    state_570425401[0].message = nimCopy(null, [65,108,114,101,97,100,121,32,119,105,116,104,105,110,32,116,104,101,32,116,97,114,103,101,116,32,114,97,110,103,101,46], NTI33554449);
    render__main_u1168();
    break BeforeRet;
    }

    state_570425401[0].autoRunning = true;
    state_570425401[0].message = nimCopy(null, autoProgressMessage__main_u1397(), NTI33554449);
    Temporary1 = HEX3Aanonymous__main_u1424.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__main_u1424; Temporary1.ClE_0 = null;
    state_570425401[0].autoTimerId = setInterval(Temporary1, 100);
    render__main_u1168();
  };


}

function setPolicySelected__main_u1456(index_p0, selected_p1) {
  BeforeRet: {
    if (((index_p0 < 0) || (15 <= index_p0))) {
    break BeforeRet;
    }

    state_570425401[0].policies[chckIndx(index_p0, 0, (state_570425401[0].policies).length - 1)].active = selected_p1;
    state_570425401[0].message = nimCopy(null, [], NTI33554449);
    render__main_u1168();
  };


}

function initApp__main_u1514() {
    var Temporary1;

function HEX3Aanonymous__main_u1515() {
    updateSlider__main_u1459();


}
    var Temporary2;

function HEX3Aanonymous__main_u1516() {
    updateAutoTarget__main_u1460();


}
    var Temporary3;

function HEX3Aanonymous__main_u1517() {
    updateAllocation__main_u1461();


}
    var Temporary4;

function HEX3Aanonymous__main_u1518() {
    updateAllocation__main_u1461();


}
    var Temporary5;

function HEX3Aanonymous__main_u1519() {
    updateAllocation__main_u1461();


}
    var Temporary6;

function HEX3Aanonymous__main_u1520() {
    playGames__main_u1370(state_570425401[0].sliderGames);


}
    var Temporary7;

function HEX3Aanonymous__main_u1521() {
    removeGames__main_u1385(state_570425401[0].sliderGames);


}
    var Temporary8;

function HEX3Aanonymous__main_u1522() {
    toggleAuto__main_u1423();


}
    var Temporary9;

function HEX3Aanonymous__main_u1523(index_p0, selected_p1) {
    setPolicySelected__main_u1456(index_p0, selected_p1);


}

    initState__main_u1488();
    Temporary1 = HEX3Aanonymous__main_u1515.bind(null); Temporary1.ClP_0 = HEX3Aanonymous__main_u1515; Temporary1.ClE_0 = null;
    document.getElementById("game-slider").addEventListener('input', Temporary1);
    Temporary2 = HEX3Aanonymous__main_u1516.bind(null); Temporary2.ClP_0 = HEX3Aanonymous__main_u1516; Temporary2.ClE_0 = null;
    document.getElementById("auto-target-slider").addEventListener('input', Temporary2);
    Temporary3 = HEX3Aanonymous__main_u1517.bind(null); Temporary3.ClP_0 = HEX3Aanonymous__main_u1517; Temporary3.ClE_0 = null;
    document.getElementById("allocation-random").addEventListener('input', Temporary3);
    Temporary4 = HEX3Aanonymous__main_u1518.bind(null); Temporary4.ClP_0 = HEX3Aanonymous__main_u1518; Temporary4.ClE_0 = null;
    document.getElementById("allocation-equalize").addEventListener('input', Temporary4);
    Temporary5 = HEX3Aanonymous__main_u1519.bind(null); Temporary5.ClP_0 = HEX3Aanonymous__main_u1519; Temporary5.ClE_0 = null;
    document.getElementById("allocation-pairings").addEventListener('input', Temporary5);
    Temporary6 = HEX3Aanonymous__main_u1520.bind(null); Temporary6.ClP_0 = HEX3Aanonymous__main_u1520; Temporary6.ClE_0 = null;
    document.getElementById("play-button").addEventListener('click', Temporary6);
    Temporary7 = HEX3Aanonymous__main_u1521.bind(null); Temporary7.ClP_0 = HEX3Aanonymous__main_u1521; Temporary7.ClE_0 = null;
    document.getElementById("remove-button").addEventListener('click', Temporary7);
    Temporary8 = HEX3Aanonymous__main_u1522.bind(null); Temporary8.ClP_0 = HEX3Aanonymous__main_u1522; Temporary8.ClE_0 = null;
    document.getElementById("auto-button").addEventListener('click', Temporary8);
    Temporary9 = HEX3Aanonymous__main_u1523.bind(null); Temporary9.ClP_0 = HEX3Aanonymous__main_u1523; Temporary9.ClE_0 = null;
    document.getElementById('policy-panel').addEventListener('change', function(event) {
  var input = event.target.closest('input[data-policy-index]');
  if (input == null) return;
  Temporary9(parseInt(input.getAttribute('data-policy-index'), 10), input.checked);
})
;
    render__main_u1168();


}
var state_570425401 = [({policies: [({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false}), ({label: [], active: false})], games: [], sliderGames: 0, targetPairGames: 0, allocationType: 0, autoRunning: false, autoTimerId: 0, autoSteps: 0, message: []})];
initApp__main_u1514();
